### ISSUE TITLE
Append entries to .gitignore file if it exisits.

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/TAF#19]
Current behaviour is to overwrite

https://github.com/ices-tools-prod/TAF/blob/17c46bdd5555180ef6918d07ae0dd330d3f8f854/R/taf.skeleton.R#L67C1-L71C32

**Comment by colinpmillar** [comment]
Also, `boot/library/`, should be `/boot/library/`

**Comment by arni-magnusson** [comment]
Great idea, now implemented in af10efa.
